### ISSUE TITLE
Wrong comparison in isOverLimit

### ISSUE THREAD

**Issue by sb-relaxt-at** [tractorcow/silverstripe-geocoding#5]
Isn't this check the wrong way around:

```
public function isOverLimit() {
    $limit = $this->getCache()->load('dailyLimit');
    if(empty($limit)) return false;     
    // It's ok if it's been 24 hours
    return (time() - $limit) > (3600 * 24);
}
```

It is consider being over limit if the passed time is smaller than 24 hours, isn't it?

**Comment by tractorcow** [comment]
No, that's within limit.

The encoding is limited FOR a period of time. After this time has passed, it's no longer limited. I.e. over that period. :D

**Comment by tractorcow** [comment]
Darn, looks like I was wrong... I re-read the code, and I'm ashamed.

This is why I should always PHPDoc my methods and return types.

**Comment by sb-relaxt-at** [comment]
You almost got me ;-). Just changing the comparison should fix it.

**Comment by tractorcow** [comment]
This is what I get for poor method naming... why did I call a method that checks if a value is UNDER a range `isOver...`.

**Comment by sb-relaxt-at** [comment]
Could be isUnderOverQuotaTimeout ;-)

**Comment by tractorcow** [comment]
I'd probably go for `wasRecentlyLimited`

**Comment by sb-relaxt-at** [comment]
Way better than my not-so-serious suggestion :-)
